name: digi_wallett
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Dependencies
  pdf: ^3.10.0
  printing: ^5.11.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.2
  get: ^4.7.3
  cloud_firestore: ^6.1.1
  image_picker: ^1.2.1
  cloudinary_sdk: ^5.0.0+1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Dev Dependencies
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

